EdgeDriver Linux/Mac
fhoeben/hsac-fitnesse-fixtures pull request #544
Opened 2023-10-09 11:36 UTC by lennyg1

2023-10-09 11:57 UTC, fhoeben requested changes
Based on the exclude https://github.com/fhoeben/hsac-fitnesse-fixtures/blob/cc58b071b6807d0b924991bb9f2762a9a27bb385/src/assembly/standalone.xml#L39C16-L39C56 I don't believe the Linux driver will be added to the standalone.zip distribution and as such I don't believe it should be mentioned here.

Do you see (a lot of) demand for testing with Edge on a Mac instead of with Chrome? Adding these drivers makes the standalone.zip larger yet. In the past I saw little push to test on anything other than Safari and Chrome for Macs from customer organizations and given the Edge and Chrome share their engine I would expect too much added value from testing with Edge on a Mac.
If I were to test specifically with Edge I would do that for Windows machines, since that's where I expect actual usage to be.

Are there big advantages testing using Edge on Mac? Or is this something you experience customer demand for?

2023-10-09 11:57 UTC, fhoeben commented on changelog.md
> +- ChromeDriver 117.0.5938.149
```suggestion
- ChromeDriver 117.0.5938.92
```

2023-10-09 11:57 UTC, fhoeben commented on changelog.md
> +- ChromeDriver
```suggestion
- ChromeDriver 117.0.5938.149
```

2023-11-01 11:00 UTC, lennyg1 commented
Chrome 119 has been released, that means that the webdrivers within HSAC are giving errors now if you use the latest Chrome. Is it possible to accept this PR?

2023-11-01 11:07 UTC, fhoeben commented
Can you remove the addition of the Mac Edge drivers, so we just have the version update? I'm not convinced yet. (And I think changing the version and adding other platforms is better kept in separate PRs anyway)

2023-11-01 16:49 UTC, lennyg1 commented
> Can you remove the addition of the Mac Edge drivers, so we just have the version update? I'm not convinced yet. (And I think changing the version and adding other platforms is better kept in separate PRs anyway)

I've had the question a few times now due to Edge increasing in popularity. Even on Linux. Still an edge case, but not impossible anymore. I'll make a new PR.

2023-11-01 16:49 UTC, closed without merging

2024-02-03 23:27 UTC, fhoeben commented
@lennyg1  I'm working on providing a separate artifact which includes the web drivers and one without. In the one with I'm planning to also add the Edge drivers for Mac