[675] Log info and errors using slf4j
fhoeben/hsac-fitnesse-fixtures pull request #676
Opened 2024-10-17 06:58 UTC by e-roeling

2024-10-17 06:59 UTC, e-roeling commented
See https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/675#issue-2593789875

2024-10-19 19:22 UTC, fhoeben requested changes

2024-10-19 19:22 UTC, fhoeben commented on src/main/java/nl/hsac/fitnesse/junit/ProgressLoggerListener.java
I don't think this should be updated as it will be used during jUnit run. I doubt slf4j is desirable there

2024-10-19 19:22 UTC, fhoeben commented on src/main/java/nl/hsac/fitnesse/junit/JUnitConsoleRunner.java
I don't think this should be updated as it will be used in `main` method launching the process from the command line. That should just use std error

2024-10-19 19:22 UTC, fhoeben commented on src/main/java/nl/hsac/fitnesse/junit/HsacFitNesseRunner.java
I don't think this should be updated as it will be used during jUnit run. I doubt slf4j is desirable there

2024-10-21 05:47 UTC, e-roeling commented on src/main/java/nl/hsac/fitnesse/junit/ProgressLoggerListener.java
I don't fully agree, but can live with it as its quite simple to use our own implementation for these.

2024-12-07 15:12 UTC, fhoeben approved these changes

2024-12-07 15:25 UTC, merged